# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-26 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20170326_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='httpResponse',
            field=models.CharField(default='', max_length=120),
        ),
    ]
