# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('c', 'Closed'), ('i', 'Empty'), ('o', 'Open'), ('f', 'Full')], default='i', help_text='Auditorium status', max_length=1)),
                ('name', models.CharField(help_text='Enter an auditorim name.', max_length=50)),
                ('address', models.CharField(default='', help_text='Enter an address.', max_length=50)),
                ('city', models.CharField(default='', help_text='Enter a city.', max_length=50)),
                ('province', models.CharField(default='', help_text='Enter a province.', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
