# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 14:53
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditorium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('c', 'Closed'), ('i', 'Empty'), ('o', 'Open'), ('f', 'Full')], default='i', help_text='Auditorium status', max_length=1)),
                ('name', models.CharField(help_text='Enter an auditorium name.', max_length=50)),
                ('image', models.URLField(blank=True, default='')),
                ('address', models.CharField(default='', help_text='Enter an address.', max_length=50)),
                ('postalCode', models.CharField(default='', help_text='Enter a postal code.', max_length=6)),
                ('city', models.CharField(default='', help_text='Enter a city.', max_length=50)),
                ('province', models.CharField(default='', help_text='Enter a province.', max_length=50)),
                ('capacity', models.IntegerField(default=0)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status'],
            },
        ),
    ]
