# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditorium',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='auditorium',
            name='postalCode',
            field=models.CharField(default='', help_text='Enter a postal code.', max_length=6),
        ),
    ]
