# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0002_auto_20170330_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='image',
            field=models.URLField(default='', null=True),
        ),
    ]
