# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0003_auto_20170330_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditorium',
            name='image',
            field=models.URLField(blank=True, default=''),
        ),
    ]
