# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Terminal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Connected', 'Connected'), ('Ready', 'Ready')], default='Connected', max_length=30)),
                ('address', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
