# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-24 22:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_terminal_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terminal',
            options={'ordering': ['id']},
        ),
    ]
