# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20170309_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='terminal',
            old_name='ipAddress',
            new_name='Address',
        ),
    ]
