# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 18:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auditorium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('i', 'In progress'), ('o', 'Open for purchase'), ('c', 'Closed')], default='i', help_text='Event status', max_length=1)),
                ('title', models.CharField(default='', help_text="Event's name", max_length=100)),
                ('sticker', models.ImageField(default='', upload_to='')),
                ('image', models.ImageField(default='', upload_to='')),
                ('artist', models.CharField(default='', help_text="Artist's name", max_length=100)),
                ('isPublished', models.BooleanField(default=False)),
                ('isOnSale', models.BooleanField(default=True)),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('duration', models.DurationField()),
                ('description', models.TextField(help_text='Enter a brief description of the event', max_length=500)),
                ('auditorium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditorium.Auditorium')),
            ],
            options={
                'ordering': ['date', '-title'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this ticket', primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('isReserved', models.BooleanField(default=False)),
                ('isSold', models.BooleanField(default=True)),
                ('event', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='event.Event')),
            ],
        ),
    ]
