# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='isSold',
            field=models.BooleanField(default=False),
        ),
    ]
