# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='ticketPrice',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
