# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='owner',
            field=models.CharField(default='', help_text='People', max_length=100),
        ),
    ]
