# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_ticketretailer_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketretailer',
            name='key',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
