# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 22:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20170220_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='isOnSale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'In progress'), ('o', 'Open for purchase'), ('c', 'Closed')], default='i', help_text='Event current status', max_length=1),
        ),
    ]
