# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-27 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_ticket_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketRetailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='retailer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.TicketRetailer'),
        ),
    ]
