# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170220_2223'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['startDate', '-name']},
        ),
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.RemoveField(
            model_name='event',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='event',
            name='sticker',
        ),
        migrations.RemoveField(
            model_name='event',
            name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default='', help_text='Event Name', max_length=120),
        ),
        migrations.AddField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='artist',
            field=models.CharField(default='', help_text='Artist Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='auditorium',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='auditorium.Auditorium'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, default='', help_text='Event Image', upload_to='uploads/images/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(blank=True, choices=[('i', 'In Progress'), ('o', 'Open for Purchase'), ('c', 'Closed')], default='i', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='event',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.Event'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, help_text='Unique ticket ID', primary_key=True, serialize=False),
        ),
    ]
