# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:47
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command

def loadfixture(apps, schema_editor):
    call_command('loaddata', 'retailers.json')
    
class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(loadfixture),
    ]
