# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20170310_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='nbTickets',
            field=models.IntegerField(default=0),
        ),
    ]
