# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 16:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20170330_1615'),
        ('event', '0004_auto_20170330_1647'),
    ]

    operations = [
    ]
