# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20170310_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 10, 12, 7, 50, 766697)),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2017, 3, 10, 12, 7, 50, 766697)),
        ),
    ]
