# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_nbtickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='nbTickets',
        ),
    ]
