# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-30 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_merge_20170330_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.URLField(default=''),
        ),
    ]
