# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 13:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_event_nbtickets'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='isUsed',
            field=models.BooleanField(default=False),
        ),
    ]
