# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-10 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_auto_20170310_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='endDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='startDate',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
